all_subjects = {'démocratie': 
['révolution citoyenne',
  'constituante',
  'révolutions',
  'électorale',
  'vote obligatoire',
  'groupe parlementaire',
  'référendum',
  'réforme'],
 'education': ['enseignement professionnel',
  'acquis',
  'transmettre le savoir',
  "conseiller principal d'éducation",
  'lire',
  "parents d'élèves",
  'discipline',
  'internat',
  'apprentissage',
  'enseignement',
  'écrire',
  "respect de l'autorité",
  'port de la blouse',
  'CPE',
  'surveillant général',
  'instruction publique',
  'compter'],
 'justice': ['justice',
  'poursuites',
  'magistrats',
  'peines planchers',
  'affaires judiciaires',
  'peine prononcée',
  'rétention',
  'majorité pénale',
  'mesures alternatives',
  'procureurs',
  'places de prison',
  'remises de peine',
  "tentatives d'homicide",
  'classement sans suite',
  'élucidation',
  'perpétuité réelle',
  'système carcéral',
  'peine plancher',
  'greffier',
  'mise sous écrou',
  'multirécidiviste',
  'bracelet éléctronique',
  'greffiers',
  'peine exécutée',
  'place de prison',
  'impunité',
  'magistrat',
  'déliquants',
  'homicides'],
 'economie': ['zone France industrielle',
  "chef d'entreprise",
  'patrie-score',
  'impôts de production',
  'démarches administratives',
  'dette',
  'protéger nos entreprises',
  'milieux populaires',
  'protectionnisme',
  'désindustrialisation',
  'retraite',
  'précarité',
  'entrepreneurs',
  'lutte travailleurs',
  'entreprise',
  'compétitivité',
  'impôt sur les sociétés'],
 'agriculture': ['élevage intensif',
  'fertilisation',
  'agriculture biologique',
  'pesticides',
  'labour',
  'pratiques agricoles',
  'OGM',
  'nourrir la planète',
  'culture des sols',
  'exploitation',
  'élevage extensif',
  'aquaculture',
  'chaîne agroalimentaire',
  'systèmes agraires',
  'agronomie',
  'exploitation de la terre',
  'élévage',
  'pastoral',
  'pastoraux',
  'sécurité alimentaire',
  'engrais',
  'irrigation',
  'élevage'],
 'ecologie': ['pesticides',
  'GIEC',
  'gaz à effet de serre',
  'voiture électrique',
  'écosystème',
  'OGM',
  'biodiversité',
  'érosion des sols',
  'impacts environnementaux',
  'Dégradation des sols',
  "respect de l'environnement",
  "pollution de l'air",
  'pollution des eaux',
  'méthane',
  'développement durable',
  'changement climatique',
  'isr',
  'lutte contre le réchauffement climatique',
  'mer',
  'esg',
  'écologie',
  'environement',
  'dioxyde de carbone'],
 'outre_mer': ['chlordécone',
  'assainissement',
  'eau potable',
  'outre mer',
  'martiniquais',
  'territoires insulaires',
  'calédonie',
  'caraïbes',
  'guadeloupéens',
  'haïti',
  'antilles'],
 'ruralité': ['monde rural',
  'mode de vie',
  'communes rurales',
  'relocalisation',
  'fibre',
  'lac',
  'campagnes',
  'rivière',
  'bourse de naissance',
  'préservation des paysages',
  'préservation de nos paysages',
  'paysages',
  'déploiement de la 4G',
  'haut-débit',
  'tradition',
  'revitalisation',
  'éoliennes',
  'chasse'],
 'europe': ['parlement européen', 'europe', 'éuropéene'],
 'immigration': ['droit du sol',
  'binationaux',
  'étrangers',
  'régulariser les clandestins',
  'stopper les flux',
  'regroupement familial',
  'mineurs non acompagnés',
  'afrique',
  'nationalité',
  'AME',
  'maroc',
  "droit d'asile",
  'tunisie',
  'algérie',
  'déchéance de nationalité',
  'islamisme',
  'entrée illégale',
  'territoire français',
  'insécurité culturelle',
  'étudiants étrangers',
  "aide médicale de l'état",
  'immigrés',
  'expulsion',
  'droit du sang',
  'renvoyer les clandestins',
  'naturalisation',
  'renvoyer les étrangers',
  'étrangers extra-européens',
  'clandestin',
  'immigration',
  'régulariser les sans-papiers',
  'afrique sub saharienne',
  'régularisation',
  'régulariser les étrangers',
  'pompes aspirantes',
  'expulser',
  'déchoir de la nationalité'],
 'identité': ['quartiers populaires',
  'culture',
  'islamisme',
  'musulmans',
  'française',
  'racisme',
  'insécurité culturelle',
  'quartiers',
  'être français',
  'fachos',
  'civilisation',
  'créolisation',
  'sentiment de dépossession',
  'francophonie',
  'islam'],
 'sécurité': ['crime',
  "forces de l'ordre",
  'justice',
  'système pénitentiaire',
  'population carcérale',
  'drogue',
  'chaine pénale',
  'délinquance',
  'escroquerie',
  'cambriolage',
  'police',
  'quartiers populaires',
  'fermeté',
  'BAC',
  'viol',
  "tentatives d'homicide",
  'violences sexuelles',
  'traffic',
  'vol',
  'agression',
  'règlement de compte',
  'déliquant',
  'criminel',
  'prison',
  'délit',
  'cité',
  'violence',
  'homicides',
  'meurtre'],
 'lutte_contre_la_fraude': ['évasion fiscale',
  'fiscale',
  'fraude sociale',
  'paradis fiscaux'],
 'santé': ['soignants',
  'dose',
  'gestes barrières',
  'maison de retraite',
  'ephad',
  'pandémie',
  'confinement',
  'ars',
  'couvre feu',
  'tests gratuits'],
 'international': ['taïwan',
  'états unis',
  'chine',
  'russie',
  'venezuela',
  'sahel',
  'pékin',
  'russes',
  'ukraine']}